---
name: eve-kernel build
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - "eve-kernel-amd64-v6.1.38-rt"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  packages:
    runs-on: self-hosted
    steps:
      - name: Get eve-kernel
        uses: actions/checkout@v3
        with:
          ref: "eve-kernel-amd64-v6.1.38-rt"
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.RELEASE_DOCKERHUB_ACCOUNT }}
          password: ${{ secrets.RELEASE_DOCKERHUB_TOKEN }}
      - name: Build eve-kernel-amd64-v6.1.38-rt
        run: |
          make -f Makefile.eve BRANCH?=${GITHUB_REF##*/} push-gcc
